<?php
/**
 * Generated configuration file
 * Generated by: phpMyAdmin 5.2.2 setup script
 * Date: Fri, 21 Feb 2025 06:52:46 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: sddb0040315177.cgidb [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'sddb0040315177.cgidb';
$cfg['Servers'][$i]['host'] = 'sddb0040315177.cgidb';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['ssl'] = true;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['only_db'] = ['sddb0040315177'];

/* End of servers configuration */

$cfg['blowfish_secret'] = \sodium_hex2bin('77f5ebfde5580797c6af973795f33ec4ec132e3f239b1926aed8f9fad61f8e9e');
$cfg['DefaultLang'] = 'ja';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';

